#!/usr/bin/env bash
# =============================================================================
# Cloudflare Tunnel — NOD Makeup backend + media
# -----------------------------------------------------------------------------
# Exposes the local API gateway (:5001) and media server (:5002) to the
# internet through ONE outbound Cloudflare named tunnel, so the Vercel-deployed
# storefront can call them over HTTPS without any open firewall ports.
#
#   api.nodmakeup.com    ->  http://127.0.0.1:5001   (/api/*, health)
#   media.nodmakeup.com  ->  http://127.0.0.1:5002   (/uploads/*, /thumbnails/*)
#
# Usage:
#   ./setup.sh            # full setup (login is skipped if already done)
#   ./setup.sh --systemd  # as above, then install a systemd service
#
# The ONLY interactive step is `cloudflared tunnel login` (browser OAuth to
# your Cloudflare account). Everything else runs non-interactively.
# =============================================================================
set -euo pipefail

CFD="cloudflared"
TUNNEL_NAME="nodmakeup-backend"
API_HOST="api.nodmakeup.com"      # -> backend :5001
MEDIA_HOST="media.nodmakeup.com"  # -> media   :5002
CFG_DIR="${HOME}/.cloudflared"
CFG_FILE="${CFG_DIR}/config.yml"

# -----------------------------------------------------------------------------
# 1. Login — needs a browser; creates cert.pem in ~/.cloudflared
# -----------------------------------------------------------------------------
if [[ ! -f "${CFG_DIR}/cert.pem" ]]; then
  echo "==> Step 1/6: cloudflared tunnel login (browser OAuth — click the printed URL)"
  ${CFD} tunnel login
else
  echo "==> Step 1/6: already logged in (${CFG_DIR}/cert.pem present) — skipping"
fi

# -----------------------------------------------------------------------------
# 2. Create the named tunnel (idempotent)
# -----------------------------------------------------------------------------
if ${CFD} tunnel list --output json | grep -q "\"name\":\"${TUNNEL_NAME}\""; then
  echo "==> Step 2/6: tunnel '${TUNNEL_NAME}' already exists — reusing"
  TUNNEL_ID=$(${CFD} tunnel list --output json | python3 -c "
import json,sys
for t in json.load(sys.stdin):
    if t['name'] == '${TUNNEL_NAME}': print(t['id'])
")
else
  echo "==> Step 2/6: creating tunnel '${TUNNEL_NAME}'"
  TUNNEL_ID=$(${CFD} tunnel create "${TUNNEL_NAME}" | grep -oE '[0-9a-f-]{36}' | head -1)
fi
CRED_FILE="${CFG_DIR}/${TUNNEL_ID}.json"
echo "     tunnel id: ${TUNNEL_ID}"
echo "     credentials: ${CRED_FILE}"
[[ -f "${CRED_FILE}" ]] || { echo "ERROR: credentials file not found: ${CRED_FILE}"; exit 1; }

# -----------------------------------------------------------------------------
# 3. Route DNS (creates CNAME api/media -> <uuid>.cfargotunnel.com)
# -----------------------------------------------------------------------------
echo "==> Step 3/6: routing DNS"
${CFD} tunnel route dns "${TUNNEL_NAME}" "${API_HOST}"   || true
${CFD} tunnel route dns "${TUNNEL_NAME}" "${MEDIA_HOST}" || true

# -----------------------------------------------------------------------------
# 4. Write config.yml with the ingress table
# -----------------------------------------------------------------------------
echo "==> Step 4/6: writing ${CFG_FILE}"
cat > "${CFG_FILE}" <<EOF
# Cloudflare Tunnel ingress — NOD Makeup (generated by scripts/tunnel/setup.sh)
tunnel: ${TUNNEL_NAME}
credentials-file: ${CRED_FILE}

ingress:
  # API gateway (Express, port 5001)
  - hostname: ${API_HOST}
    service: http://127.0.0.1:5001

  # Media server (port 5002): /uploads and /thumbnails only
  - hostname: ${MEDIA_HOST}
    service: http://127.0.0.1:5002

  # Everything else: reject
  - service: http_status:404
EOF

# -----------------------------------------------------------------------------
# 5. Validate the ingress rules
# -----------------------------------------------------------------------------
echo "==> Step 5/6: validating ingress"
${CFD} tunnel ingress validate

# -----------------------------------------------------------------------------
# 6. Run (foreground by default, or systemd service with --systemd)
# -----------------------------------------------------------------------------
echo
echo "==> Step 6/6:"
if [[ "${1:-}" == "--systemd" ]]; then
  echo "    Installing systemd service (requires sudo):"
  sudo ${CFD} service install
  sudo systemctl enable cloudflared
  sudo systemctl start cloudflared
  sudo systemctl status cloudflared --no-pager | head -12
else
  echo "    Starting foreground. Ctrl+C to stop."
  echo "    Once happy, re-run with: ./setup.sh --systemd"
  echo
  exec ${CFD} tunnel run "${TUNNEL_NAME}"
fi

# -----------------------------------------------------------------------------
echo
echo "✅ Tunnel live. Verify from the public internet:"
echo "   curl -s -o /dev/null -w '%{http_code}\n' https://${API_HOST}/api/v1/orders/shipping-zones -H 'Origin: https://nodmakeup.vercel.app'"
echo "   curl -s -o /dev/null -w '%{http_code}\n' https://${MEDIA_HOST}/thumbnails/thumb-story-1762642070224.png   # expect 200 image/png"
echo
echo "Then set these in the Vercel project dashboard  (Settings -> Environment Variables -> Production):"
echo "   NEXT_PUBLIC_GATEWAY_URL = https://${API_HOST}"
echo "   NEXT_PUBLIC_MEDIA_BASE_URL = https://${MEDIA_HOST}"
echo "and redeploy. The GitHub push of the storefront is queued until the tunnel responds."