#!/usr/bin/env node
/**
 * NOD Makeup — single source of truth for ALL environment configuration.
 *
 *  .env                          <- edit ONLY this file (repo root)
 *     ├─ backend/.env            (server env, forwarded + validated)
 *     ├─ media-server/.env       (media env)
 *     ├─ admin-panel/.env        (CRA public vars: REACT_APP_*)
 *     ├─ admin-panel/.env.development (dev server override — same values)
 *     ├─ main-website/.env       (Next public vars: NEXT_PUBLIC_*)
 *     └─ deploy/.env             (production compose secrets + URLs)
 *
 * Every key name comes from @nod/shared/runtime/config (ENV_CONTRACT) — the
 * same contract the backend, media-server, admin panel and storefront read.
 * Keys that exist in the root file but are unknown are forwarded to the
 * backend .env unchanged (safe passthrough) rather than silently dropped.
 *
 * Usage:
 *   node scripts/sync-env.mjs                      # render from .env (prod)
 *   node scripts/sync-env.mjs --init               # build .env from old
 *                                                  # per-service files, then render
 *   node scripts/sync-env.mjs --base 192.168.1.18 --proto http \
 *        --admin-port 3000 --web-port 3001 \       # dev host → SAFE_ORIGINS merge
 *        --media-port 5002 --backend-port 5001
 */

import { createRequire } from 'node:module';
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { randomBytes } from 'node:crypto';

const require = createRequire(import.meta.url);
const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const ROOT_ENV = resolve(ROOT, '.env');
const SHARED_DIST = resolve(ROOT, 'shared/dist/runtime/config');
const { ENV_CONTRACT, defaultPortOf, parseOriginList } = require(SHARED_DIST);

const GENERATED_HEADER = `# ══════════════════════════════════════════════════════════════
# GENERATED by scripts/sync-env.mjs from the root .env (single source).
# DO NOT EDIT BY HAND — every key is derived from ../../.env. Run again
# after any change to the root file.
# ══════════════════════════════════════════════════════════════
`;

// ---- CLI args ----
const args = process.argv.slice(2);
const opt = {
  init: false,
  base: null,
  proto: 'http',
  adminPort: 3000,
  webPort: 3001,
  mediaPort: null,
};
for (let i = 0; i < args.length; i++) {
  const a = args[i];
  if (a === '--init') opt.init = true;
  else if (a === '--base') opt.base = args[++i];
  else if (a === '--proto') opt.proto = args[++i];
  else if (a === '--admin-port') opt.adminPort = args[++i];
  else if (a === '--web-port') opt.webPort = args[++i];
  else if (a === '--media-port') opt.mediaPort = args[++i];
  else if (a === '--backend-port') opt.backendPort = args[++i];
  else { console.error(`Unknown option: ${a}`); process.exit(1); }
}

// ---- helpers ----
function parseEnv(text) {
  const out = {};
  for (const line of text.replace(/\r\n/g, '\n').split('\n')) {
    const m = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)\s*$/);
    if (!m) continue;
    let val = m[2].trim();
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    if (val.includes('#') && !val.includes(' ')) val = val.split('#')[0].trim();
    out[m[1]] = val;
  }
  return out;
}

function readOrEmpty(file) {
  try {
    return parseEnv(readFileSync(file, 'utf8'));
  } catch {
    return {};
  }
}

function joinList(values) {
  return [...new Set(values.map((s) => s.trim()).filter(Boolean))].join(',');
}

// ---- step 0: build root .env from legacy per-service files (--init) ----
if (opt.init) {
  if (existsSync(ROOT_ENV)) {
    console.log('sync-env: .env already exists — skipping --init (nothing merged).');
  } else {
    const fragments = [
      ROOT_ENV,
      resolve(ROOT, 'deploy/.env.example'),
      resolve(ROOT, 'backend/.env.example'),
      resolve(ROOT, 'media-server/.env'),
      resolve(ROOT, 'deploy/.env'),
      resolve(ROOT, 'backend/.env'),
    ];
    const merged = {};
    for (const f of fragments) Object.assign(merged, readOrEmpty(f));
    // Sensible missing defaults (never overwrite merged secrets).
    for (const k of ['PORT', 'STORE_URL']) if (!merged[k]) merged[k] = k === 'PORT' ? '5001' : '';
    writeFileSync(
      ROOT_ENV,
      `# NOD Makeup — SINGLE SOURCE OF TRUTH for ALL services.\n# Edit THIS file; run \`node scripts/sync-env.mjs\` to regenerate.\n\n${Object.entries(merged)
        .map(([k, v]) => `${k}=${v}`)
        .join('\n')}\n`,
    );
    console.log(`sync-env: initialized ${ROOT_ENV} from existing per-service env files.`);
  }
}

if (!existsSync(ROOT_ENV)) {
  console.error('sync-env: missing root .env. Run with --init to bootstrap from existing files.');
  process.exit(1);
}

const root = parseEnv(readFileSync(ROOT_ENV, 'utf8'));

// ---- SAFE_ORIGINS: dev host merge ----
const devOrigins = new Set();
if (opt.base) {
  const b = opt.base;
  if (b === 'localhost') {
    devOrigins.add('http://localhost:3000');
    devOrigins.add('http://localhost:3001');
  } else {
    const proto = opt.proto || 'http';
    devOrigins.add(`${proto}://${b}:${opt.adminPort}`);
    devOrigins.add(`${proto}://${b}:${opt.webPort}`);
  }
}
if (devOrigins.size) {
  const mergedOrigins = joinList([...(parseOriginList(root.SAFE_ORIGINS) || []), ...devOrigins]);
  if (root.SAFE_ORIGINS !== mergedOrigins) {
    root.SAFE_ORIGINS = mergedOrigins;
    writeFileSync(
      ROOT_ENV,
      Object.entries(root)
        .map(([k, v]) => `${k}=${v}`)
        .join('\n') + '\n',
    );
    console.log(`sync-env: SAFE_ORIGINS updated in .env -> ${mergedOrigins}`);
  }
}

// ---- Api .env ----
const apiForward = new Set([
  ...Object.values(ENV_CONTRACT.api.keys),
  'DATABASE_URL',
  'REDIS_URL',
  'JWT_SECRET',
  'JWT_EXPIRES_IN',
  'MEDIA_API_KEY',
  'TELEGRAM_BOT_TOKEN',
  'TELEGRAM_ADMIN_CHAT_ID',
  'AI_ENABLED',
  'OLLAMA_URL',
  'OLLAMA_MODEL',
  'SENTRY_DSN',
  'SERVICE_NAME',
  'LOG_LEVEL',
  'NODE_ENV',
]);
const apiEnv = Object.keys(root)
  .filter((k) => apiForward.has(k))
  .map((k) => `${k}=${root[k]}`);
const required = ['DATABASE_URL', 'REDIS_URL', 'JWT_SECRET', 'GATEWAY_URL', 'MEDIA_BASE_URL', 'ADMIN_PANEL_URL', 'SAFE_ORIGINS'];
const missing = required.filter((k) => !root[k] || root[k].startsWith('CHANGE_ME') || root[k] === '');
if (missing.length) {
  console.error(`sync-env: root .env is missing required values: ${missing.join(', ')}`);
  process.exit(1);
}

// ---- Media .env ----
const mediaPort = opt.mediaPort || root.MEDIA_PORT || String(defaultPortOf('media'));
const mediaEnv = [
  `PORT=${mediaPort}`,
  `MEDIA_BASE_URL=${root.MEDIA_BASE_URL || ''}`,
  `SAFE_ORIGINS=${root.SAFE_ORIGINS || ''}`,
  `MEDIA_API_KEY=${root.MEDIA_API_KEY || ''}`,
];

// ---- Admin .env (CRA public vars) ----
const adminVars = [
  `REACT_APP_API_URL=${root.GATEWAY_URL || ''}`,
  `REACT_APP_MEDIA_URL=${root.MEDIA_BASE_URL || ''}`,
];

// ---- Storefront .env (Next public vars) ----
const storeVars = [
  `NEXT_PUBLIC_GATEWAY_URL=${root.GATEWAY_URL || ''}`,
  `NEXT_PUBLIC_MEDIA_BASE_URL=${root.MEDIA_BASE_URL || ''}`,
  `ALLOWED_DEV_ORIGINS=${root.SAFE_ORIGINS || ''}`,
];

// ---- deploy/.env (production compose) ----
function ensureSecret(key, len = 48) {
  if (root[key] && !String(root[key]).startsWith('CHANGE_ME')) return root[key];
  const secret = randomBytes(Math.ceil(len / 2)).toString('hex').slice(0, len);
  root[key] = secret;
  return secret;
}
const deployVars = [
  'MYSQL_ROOT_PASSWORD=' + ensureSecret('MYSQL_ROOT_PASSWORD', 32),
  'MYSQL_PASSWORD=' + ensureSecret('MYSQL_PASSWORD', 32),
  `JWT_SECRET=${root.JWT_SECRET || ''}`,
  `JWT_EXPIRES_IN=${root.JWT_EXPIRES_IN || '1d'}`,
  `MEDIA_API_KEY=${root.MEDIA_API_KEY || ''}`,
  `TELEGRAM_BOT_TOKEN=${root.TELEGRAM_BOT_TOKEN || ''}`,
  `TELEGRAM_ADMIN_CHAT_ID=${root.TELEGRAM_ADMIN_CHAT_ID || ''}`,
  `AI_ENABLED=${root.AI_ENABLED || 'false'}`,
  `OLLAMA_URL=${root.OLLAMA_URL || 'http://host.docker.internal:11434'}`,
  `OLLAMA_MODEL=${root.OLLAMA_MODEL || 'llama3.2'}`,
  `GRAFANA_ADMIN_PASSWORD=${ensureSecret('GRAFANA_ADMIN_PASSWORD', 32)}`,
  `MYSQL_EXPORTER_PASSWORD=${ensureSecret('MYSQL_EXPORTER_PASSWORD', 32)}`,
  `BACKUP_PASSPHRASE=${ensureSecret('BACKUP_PASSPHRASE', 32)}`,
  `RCLONE_REMOTE=${root.RCLONE_REMOTE || 'r2:nod-backups'}`,
  `GATEWAY_URL=${root.GATEWAY_URL || ''}`,
  `MEDIA_BASE_URL=${root.MEDIA_BASE_URL || ''}`,
  `ADMIN_PANEL_URL=${root.ADMIN_PANEL_URL || ''}`,
  `SAFE_ORIGINS=${root.SAFE_ORIGINS || ''}`,
];

// ---- write outputs ----
const outputs = [
  [resolve(ROOT, 'backend/.env'), apiEnv.join('\n')],
  [resolve(ROOT, 'media-server/.env'), mediaEnv.join('\n')],
  [resolve(ROOT, 'admin-panel/.env'), adminVars.join('\n')],
  [resolve(ROOT, 'admin-panel/.env.development'), adminVars.join('\n')],
  [resolve(ROOT, 'main-website/.env'), storeVars.join('\n')],
  [resolve(ROOT, 'deploy/.env'), deployVars.join('\n')],
];
for (const [file, body] of outputs) {
  writeFileSync(file, GENERATED_HEADER + body + '\n');
  console.log(`sync-env: wrote ${file.replace(ROOT + '/', '')}`);
}

// Backend keeps its canonical key names in sync with ENV_CONTRACT; if the root
// carries a legacy key asked for nowhere, it is simply not forwarded. Report it.
const unused = Object.keys(root).filter((k) => !apiForward.has(k) && !['MEDIA_PORT', 'STORE_URL', 'MYSQL_ROOT_PASSWORD', 'MYSQL_PASSWORD', 'GRAFANA_ADMIN_PASSWORD', 'MYSQL_EXPORTER_PASSWORD', 'BACKUP_PASSPHRASE', 'RCLONE_REMOTE'].includes(k));
if (unused.length) console.log(`sync-env: root keys not in any contract (ignored): ${unused.join(', ')}`);

console.log('sync-env: done. Single source = .env');